/* EngBook v0.73 — Lesson 03 complete adaptive park learning journey. */
(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const q=s=>String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ');
  const PM=root.EngBookPersonalMarks;
  const TAX=root.EngBookHotspotTaxonomy;
  const classifier=h=>{
    if(h?.categoryKey)return h.categoryKey;
    const id=String(h?.id||''),t=String(h?.type||'').toLowerCase(),g=String(h?.detailGroup||'').toLowerCase(),a=String(h?.attributeGroup||'').toLowerCase(),e=String(h?.en||'').toLowerCase(),p=String(h?.parentId||'');
    if(h?.level!=='detail'){
      if(id==='l03-boy-left'||id==='l03-girl-right')return 'children';
      if(id==='l03-joined-hands')return 'actions';
      if(id==='l03-playground')return 'playground';
      if(['l03-path','l03-lawn','l03-flowers','l03-fountain'].includes(id))return 'nature';
      if(id==='l03-visitors')return 'background';
      return 'overview';
    }
    if(t==='light'||g==='light'||['lighting','shadow','sun-glow','haze','rim-light','canopy-light'].includes(a)||/sunlight|sunlit|shadow|glow|highlight|haze|rim light/.test(e))return 'light';
    if(t==='action'||['gesture','interaction'].includes(g)||['action','arm','posture','gait','movement','body-angle','expression','arm-position','hand-shape','hand-detail'].includes(a)||/running|holding|joined|stride|lifted feet|open .* hand|fingers|mutual smiles|body angle/.test(e))return 'actions';
    if(p==='l03-playground'||g==='structure'||['roof','slide','posts','railing','panel','platform','roof-detail','roof-shape','shadow-detail','slide-detail','slide-opening','slide-shape','opening','railing-detail','platform-detail'].includes(a))return 'playground';
    if(['shirt','lower-body','dress','shoes','hair-accessories'].includes(g)||t==='clothing'||['garment','neckline','sleeve','pocket','shorts','length','footwear','bow','strap','texture','waist','skirt','trim','detail','fabric-folds','hem','bodice'].includes(a))return 'clothing';
    if(['l03-path','l03-lawn','l03-flowers','l03-fountain'].includes(p)||['ground','vegetation','water'].includes(g)||t==='setting'||t==='nature')return 'nature';
    if(p==='l03-visitors'||['background-people','background-objects'].includes(g)||['person','bench','clothing','group','bench-detail'].includes(a))return 'background';
    return 'children';
  };
  const config={profile:'children-park-play',defaultCategory:'overview',categories:[
    {key:'overview',label:'Overview'},{key:'children',label:'Children & Faces'},{key:'clothing',label:'Clothing & Details'},{key:'actions',label:'Actions & Movement'},{key:'playground',label:'Playground'},{key:'nature',label:'Park & Nature'},{key:'background',label:'Visitors & Objects'},{key:'light',label:'Light & Atmosphere'}
  ],classifier};
  const dataTax=root.EngBookContent?.getPack?.(3)?.presentation?.hotspotTaxonomy;if(dataTax?.categories?.length){config.profile=dataTax.profile||config.profile;config.defaultCategory=dataTax.defaultCategory||config.defaultCategory;config.categories=dataTax.categories;}
  TAX?.register?.(3,config);
  const categoryKey=()=>{const k=state.hotspotCategoryByLesson?.[3]||'overview';return config.categories.some(x=>x.key===k)?k:'overview';};
  const catLabel=h=>config.categories.find(x=>x.key===classifier(h))?.label||'Detail';
  const entries=(key=categoryKey())=>{const hs=state.lesson?.hotspots||[];if(key==='overview')return hs.map((h,index)=>({h,index})).filter(({h})=>h.level!=='detail');return hs.map((h,index)=>({h,index})).filter(({h})=>classifier(h)===key);};
  function savedHotspot(h){if(!PM)return false;const t=PM.target({lessonId:3,type:'hotspot',id:h?.id||h?.en||'hotspot'}),x=PM.find(progress,t);return !!(x&&(x.marked||x.highlighted));}
  function markedCount(){return (state.lesson?.hotspots||[]).filter(savedHotspot).length;}
  function bar(){const k=categoryKey(),marked=markedCount();return `<nav class="v67-hotspot-categories v69-adaptive-categories v73-park-taxonomy" aria-label="Hotspot categories"><div class="v67-hotspot-category-scroll">${config.categories.map(c=>`<button class="${!state.personalMarkFilter&&k===c.key?'active':''}" data-eng-v52-click="event.stopPropagation();setAdaptiveHotspotCategory('${c.key}')"><b>${esc(c.label)}</b><span>${entries(c.key).length}</span></button>`).join('')}<button class="v70-my-marks ${state.personalMarkFilter?'active':''}" data-eng-v52-click="event.stopPropagation();showMarkedHotspots()"><b>My Marks</b><span>${marked}</span></button></div><small>${state.personalMarkFilter?`Showing ${marked} personal marked/highlighted hotspot${marked===1?'':'s'}.`:k==='overview'?'Choose a layer to reveal only related park details.':`Showing ${entries(k).length} ${esc(config.categories.find(x=>x.key===k)?.label||k)} anchors.`}</small></nav>`;}

  const _visible=v35VisibleHotspots;
  v35VisibleHotspots=function(){if(activeLessonId()===3&&state.mode==='explore'&&!state.personalMarkFilter)return entries();return _visible();};
  const _parent=v35DetailParent;
  v35DetailParent=function(){if(activeLessonId()===3&&state.mode==='explore')return null;return _parent();};
  const directCard=v60OpenHotspotCard;
  root.v73OpenWordCard=i=>directCard(Number(i));
  v60OpenHotspotCard=function(i){if(activeLessonId()===3&&state.mode==='explore')return v60SelectAnchor(Number(i));return directCard(Number(i));};

  const _panel=v60MicroPanel;
  v60MicroPanel=function(h){let html=_panel(h);if(activeLessonId()!==3||!h)return html;const label=catLabel(h).toUpperCase();html=html.replace('SCENE WORD',`${esc(label)} HOTSPOT`).replace('<em class="v70-category-chip">Detail</em>',`<em class="v70-category-chip">${esc(catLabel(h))}</em>`);if(!html.includes('v69-glass-tag'))html=html.replace('<section class="v60-scene-example',`<section class="v60-scene-example`).replace('<span>EXAMPLE FROM THIS PHOTO</span>',`<span>EXAMPLE FROM THIS PHOTO</span><i class="v69-glass-tag">${esc(label)}</i>`);html=html.replace('The example sentence is tied to the selected visual detail.','This sentence is directly tied to the selected part of the park image.');return html;};

  const _stage=sceneStage;
  sceneStage=function(modal=false){let html=_stage(modal);if(activeLessonId()!==3||state.mode!=='explore')return html;html=html.replace('<div class="photo-top-actions">',`${bar()}<div class="photo-top-actions">`);const sel=state.lesson?.hotspots?.[Number(state.selected)];if(sel){html=html.replaceAll(`data-eng-v52-click="event.stopPropagation();v60OpenHotspotCard(${state.selected})"`,`data-eng-v52-click="event.stopPropagation();v73OpenWordCard(${state.selected})"`);html=html.replace('<small>tap word</small>',`<small>${esc(catLabel(sel).toUpperCase())} • tap word</small>`);}html=html.replace('<span>MICRO HOTSPOT MODE</span>',`<span>${esc((state.personalMarkFilter?'MY MARKS':categoryKey()).toUpperCase())} HOTSPOTS</span>`);return html;};

  // Correct Lesson 03 mark metadata so My Marks keeps the adaptive park category.
  function hTarget(h){return PM?.target({lessonId:3,type:'hotspot',id:h?.id||h?.en||'hotspot'});}
  function hMeta(h){const ex=(activeGold()?.hotspotDetailsById?.[h?.id]||activeGold()?.hotspotDetails?.[h?.en]||{});return {label:h?.en||'',text:h?.example||ex.grammar||'',category:catLabel(h)};}
  const _toggleMark=root.toggleHotspotMark,_toggleHi=root.toggleHotspotHighlight;
  root.toggleHotspotMark=function(){if(activeLessonId()!==3||!PM)return _toggleMark?.();const h=state.lesson?.hotspots?.[Number(state.selected)];if(!h)return;const t=hTarget(h),before=PM.isMarked(progress,t);PM.toggleMark(progress,t,hMeta(h));saveProgress();haptic(9);toast(before?'Removed from My Marks':'Added to My Marks');render();};
  root.toggleHotspotHighlight=function(){if(activeLessonId()!==3||!PM)return _toggleHi?.();const h=state.lesson?.hotspots?.[Number(state.selected)];if(!h)return;const t=hTarget(h),before=PM.isHighlighted(progress,t);PM.toggleHighlight(progress,t,hMeta(h));saveProgress();haptic(8);toast(before?'Highlight removed':'Sentence highlighted');render();};

  // Lesson 03 source data and personal mark helpers.
  root.setL03JourneyStep=function(step){const valid=['overview','micro','build','scenario','meaning','story','language','grammar','speak'];state.l03JourneyStep=valid.includes(step)?step:'overview';render();};
  const g=()=>activeGold();
  const next=(step,label='Continue')=>`<button class="l01-next" data-eng-v52-click="setL03JourneyStep('${step}')">${esc(label)} ${icon('chevron')}</button>`;
  const nav=()=>`<div class="l01-journey-nav">${[['overview','01','Scene'],['micro','02','Analyze'],['build','03','Build'],['scenario','04','Combine'],['meaning','05','Reason'],['story','06','Story'],['language','07','Language'],['grammar','08','Grammar'],['speak','09','Speak']].map(([k,n,t])=>`<button class="${state.l03JourneyStep===k?'active':''}" data-eng-v52-click="setL03JourneyStep('${k}')"><i>${n}</i><span>${t}</span></button>`).join('')}</div>`;
  function status(type,id){if(!PM)return {marked:false,highlighted:false,key:''};const t=PM.target({lessonId:3,type,id}),x=PM.find(progress,t)||{};return {marked:!!x.marked,highlighted:!!x.highlighted,key:t.key};}
  function tools(type,id,label,text,category){const s=status(type,id);return `<div class="v72-inline-tools"><button class="${s.marked?'active mark':''}" data-eng-v52-click="togglePersonalContentMark('${q(type)}','${q(id)}','${q(label)}','${q(text)}','${q(category)}')">${s.marked?'★':'☆'} <span>${s.marked?'Marked':'Mark'}</span></button><button class="${s.highlighted?'active highlight':''}" data-eng-v52-click="togglePersonalContentHighlight('${q(type)}','${q(id)}','${q(label)}','${q(text)}','${q(category)}')">▰ <span>${s.highlighted?'Highlighted':'Highlight'}</span></button></div>`;}
  const cls=(type,id)=>{const s=status(type,id);return `${s.marked?' v72-is-marked':''}${s.highlighted?' v72-is-highlighted':''}`;};

  function overview(c){return `<section class="l01-step l01-overview-step"><div class="l01-source-badge"><i>${icon('compass')}</i><div><b>VISUAL LEARNING PATH</b><span>Lesson 03 • Siblings Playing</span></div></div><div class="l01-overview-grid"><article class="l01-overview-photo"><img src="${state.lesson.image}" alt="${esc(state.lesson.title)}"><div><span>OBSERVE FIRST</span><b>children • movement • playground • park clues</b></div></article><article class="l01-overview-copy"><span>01 • SCENE OVERVIEW</span><h2>Read the movement first, then build the park around it.</h2><p>${esc(c.overview)}</p><div class="l01-overview-actions"><button data-eng-v52-click="speak('${q(c.overview)}',.88)">${icon('volume')} Listen</button><button data-eng-v52-click="setMode('explore')">Open full-screen scene ${icon('expand')}</button></div><div class="l01-scene-formula"><span><b>WHO</b>two children</span><i>→</i><span><b>ACTION</b>running + holding hands</span><i>→</i><span><b>WHERE</b>park beside a playground</span><i>→</i><span><b>CLUES</b>flowers + fountain</span></div></article></div>${next('micro','Analyze the picture')}</section>`;}
  function micro(c){return `<section class="l01-step"><div class="l01-step-head"><span>02 • VISUAL EVIDENCE & MICRO-ANALYSIS</span><h2>Move from the whole park to details you can point to.</h2><p>Use facial expression, clothing, body position, playground objects, park features and light as separate evidence layers.</p></div><div class="l01-analysis-grid"><div class="l01-evidence-stack">${(c.evidence||[]).map((r,i)=>`<details ${i<3?'open':''}><summary><i>${String(i+1).padStart(2,'0')}</i><b>${esc(r.label)}</b>${icon('chevron')}</summary><p>${esc(r.detail)}</p></details>`).join('')}</div><aside class="l01-micro-aside"><span>SUBJECT MICRO-ANALYSIS</span>${(c.micro||[]).map((m,i)=>`<article><i>${i+1}</i><p>${esc(m)}</p></article>`).join('')}<button data-eng-v52-click="setMode('explore')">Inspect ${state.lesson?.hotspots?.length||0} categorized hotspots ${icon('target')}</button><small>Only one semantic layer is shown at a time so the park image stays readable.</small></aside></div>${next('build','Build sentences')}</section>`;}

  // Lesson-specific builder engine: use Lesson 03 builder sentences, never Lesson 01 defaults.
  const bSets=()=>Array.isArray(g()?.recall?.builderSentences)?g().recall.builderSentences:[];
  const _initBuilder=initBuilder,_checkBuilder=checkBuilder,_nextBuilder=nextBuilder,_builderContent=builderContent;
  initBuilder=function(){if(activeLessonId()!==3)return _initBuilder();const sets=bSets(),parts=sets[state.builderIndex%sets.length]||[];state.builderAvailable=shuffle(parts.map((_,i)=>i));state.builderChosen=[];state.builderResult='';};
  checkBuilder=function(){if(activeLessonId()!==3)return _checkBuilder();const sets=bSets(),parts=sets[state.builderIndex%sets.length]||[],ok=state.builderChosen.length===parts.length&&state.builderChosen.every((id,i)=>id===i);state.builderResult=ok?'correct':'wrong';haptic(ok?[15,25,40]:25);if(ok){awardPoints(10,'builder');speak(parts.join(' '));}render();};
  nextBuilder=function(){if(activeLessonId()!==3)return _nextBuilder();const sets=bSets();state.builderIndex=(state.builderIndex+1)%sets.length;initBuilder();render();};
  builderContent=function(){if(activeLessonId()!==3)return _builderContent();const sets=bSets(),parts=sets[state.builderIndex%sets.length]||[],text=parts.join(' '),id=`builder-${state.builderIndex}`,s=status('sentence',id);return `<div class="builder-card l01-inline-builder"><div class="builder-head"><div><span>SCENE SENTENCE ${state.builderIndex+1}/${sets.length}</span><h3>Build the sentence from meaning chunks</h3><p>Use visible park evidence before adding interpretation.</p></div><button data-eng-v52-click="builderReset()">${icon('reset')} Reset</button></div><div class="v72-builder-save${cls('sentence',id)}" data-personal-key="${esc(s.key)}"><div><span>PERSONAL NOTEBOOK</span><b>${esc(text)}</b></div>${tools('sentence',id,`Sentence Builder ${state.builderIndex+1}`,text,'Sentence Builder')}</div><div class="answer-zone ${state.builderResult}">${state.builderChosen.length?state.builderChosen.map(i=>`<button data-eng-v52-click="builderUndo()">${esc(parts[i])}</button>`).join(''):'<span>Tap the chunks below in the right order…</span>'}</div><div class="token-bank">${state.builderAvailable.map(i=>`<button data-eng-v52-click="builderPick(${i})">${esc(parts[i])}</button>`).join('')}</div><div class="builder-actions"><button class="secondary" data-eng-v52-click="builderUndo()" ${!state.builderChosen.length?'disabled':''}>Undo</button><button class="primary" data-eng-v52-click="checkBuilder()">Check sentence</button></div>${state.builderResult==='correct'?`<div class="builder-feedback good">${icon('check')} Correct. <button data-eng-v52-click="nextBuilder()">Next sentence →</button></div>`:state.builderResult==='wrong'?'<div class="builder-feedback try">Not quite. Rebuild the chunks in natural English order.</div>':''}</div>`;};
  function build(c){if(!state.builderAvailable.length&&!state.builderChosen.length)initBuilder();const rows=(c.recall?.builderSentences||[]);return `<section class="l01-step"><div class="l01-step-head"><span>03 • SENTENCE BUILDING</span><h2>Connect children, movement, clothing and place.</h2><p>Build from visible facts first, then use cautious language only when you move beyond the frame.</p></div><div class="l01-sentence-ladder v72-sentence-ladder">${rows.map((parts,i)=>{const text=parts.join(' '),id=`builder-${i}`,s=status('sentence',id);return `<article class="${cls('sentence',id)}" data-personal-key="${esc(s.key)}"><i>S${i+1}</i><p>${esc(text)}</p><div class="v72-row-actions"><button data-eng-v52-click="speak('${q(text)}',.84)">${icon('volume')} Listen</button>${tools('sentence',id,`Sentence Builder ${i+1}`,text,'Sentence Builder')}</div></article>`;}).join('')}</div>${builderContent()}${next('scenario','Combine scene details')}</section>`;}
  function scenario(c){return `<section class="l01-step v69-scenario-step"><div class="l01-step-head"><span>04 • SCENE COMBINATIONS</span><h2>Combine hotspot layers into natural park descriptions.</h2><p>Each card joins details from different hotspot categories without inventing unseen people, ages or history.</p></div><div class="v69-scenario-grid">${(c.sceneCombinations||[]).map((x,i)=>{const id=`scenario-${i}`,s=status('scenario',id);return `<article class="${x.kind==='inference'?'inference':'fact'} ${cls('scenario',id)}" data-personal-key="${esc(s.key)}"><div class="v69-scenario-head"><i>${String(i+1).padStart(2,'0')}</i><div><b>${esc(x.title)}</b><div>${(x.categories||[]).map(k=>`<span>${esc(config.categories.find(v=>v.key===k)?.label||k)}</span>`).join('')}</div></div><em>${x.kind==='inference'?'CAUTIOUS INFERENCE':'VISIBLE FACTS'}</em></div><p>${esc(x.sentence)}</p><div class="v70-scenario-actions"><button data-eng-v52-click="speak('${q(x.sentence)}',.84)">${icon('volume')} Listen</button>${tools('scenario',id,x.title,x.sentence,'Scene Combination')}</div></article>`;}).join('')}</div><div class="v69-combine-rule"><b>Combination rule</b><p>Join subject + action + place first. Add mood or relationship only when the visible clue is named.</p></div>${next('meaning','Check fact vs inference')}</section>`;}

  root.l03AnswerFact=function(kind){const items=g()?.recall?.factItems||[];if(!items.length)return;state.factIndex=state.factIndex%items.length;const item=items[state.factIndex],ok=kind===item.kind;state.factAnswered={ok,kind};if(ok)state.factScore++;haptic(ok?[15,25,30]:22);render();};
  root.l03NextFact=function(){const items=g()?.recall?.factItems||[];if(state.factIndex<items.length-1){state.factIndex++;state.factAnswered=null;}else{toast(`Evidence check complete: ${state.factScore}/${items.length}`);state.factIndex=0;state.factAnswered=null;state.factScore=0;}render();};
  function fact(c){const items=c.recall?.factItems||[];state.factIndex=state.factIndex%Math.max(1,items.length);const item=items[state.factIndex];if(!item)return '';return `<div class="fact-game l01-three-way-fact"><div class="fact-counter"><span>EVIDENCE CHECK ${state.factIndex+1}/${items.length}</span><b>${state.factScore} correct</b></div><article><div class="quote-mark">“</div><h3>${esc(item.text)}</h3><p>Classify the sentence by what this single park photograph can actually support.</p></article><div class="fact-actions three"><button data-eng-v52-click="l03AnswerFact('fact')" ${state.factAnswered?'disabled':''}>${icon('eye')} Visible fact</button><button data-eng-v52-click="l03AnswerFact('inference')" ${state.factAnswered?'disabled':''}>${icon('layers')} Supported inference</button><button data-eng-v52-click="l03AnswerFact('unsupported')" ${state.factAnswered?'disabled':''}>${icon('close')} Unsupported</button></div>${state.factAnswered?`<div class="fact-feedback ${state.factAnswered.ok?'good':'try'}"><b>${state.factAnswered.ok?'Correct':'Check the evidence again'}</b><p>${esc(item.note)}</p><button data-eng-v52-click="l03NextFact()">${state.factIndex===items.length-1?'Finish':'Next'} →</button></div>`:''}</div>`;}
  function meaning(c){return `<section class="l01-step"><div class="l01-step-head"><span>05 • INTERPRETATION & EVIDENCE</span><h2>Keep visible play separate from family assumptions.</h2></div><div class="confidence-ladder l01-confidence"><article class="confidence-card high"><div><b>HIGH</b><span>Strongly supported</span></div><p>${esc(c.inference.high)}</p></article><article class="confidence-card medium"><div><b>MEDIUM</b><span>Plausible</span></div><p>${esc(c.inference.medium)}</p></article><article class="confidence-card low"><div><b>LOW</b><span>Weak / unlinked</span></div><p>${esc(c.inference.low)}</p></article></div><div class="timeline-pro l01-timeline"><article><span>BEFORE · HYPOTHESIS</span><p>${esc(c.timeline.before)}</p></article><i>${icon('chevron')}</i><article><span>NOW · VISIBLE</span><p>${esc(c.timeline.now)}</p></article><i>${icon('chevron')}</i><article><span>NEXT · POSSIBILITY</span><p>${esc(c.timeline.next)}</p></article></div><div class="accuracy-card l01-guardrail"><div>${icon('target')}<b>Accuracy guardrail</b></div><p>${esc(c.guardrail)}</p></div>${fact(c)}${next('story','Build a possible story')}</section>`;}
  function story(c){const text=String(c.story||'').replace(/^CREATIVE EXTENSION — NOT A VISUAL FACT\.\s*/,'');return `<section class="l01-step"><div class="l01-step-head"><span>06 • STORY BUILDER</span><h2>Extend the moment while keeping imagination labeled.</h2></div><div class="l01-story-card"><div class="l01-story-warning">${icon('spark')}<span><b>CREATIVE EXTENSION — NOT A VISUAL FACT</b><small>Use may / might / could for events outside the frame.</small></span></div><p>${esc(text)}</p><button data-eng-v52-click="speak('${q(text)}',.86)">${icon('volume')} Listen</button></div><div class="l01-story-contrast"><article><span>PHOTO CAN SUPPORT</span><p>${esc(c.timeline.now)}</p></article><article><span>STORY CAN IMAGINE</span><p>${esc(c.timeline.before)} ${esc(c.timeline.next)}</p></article></div>${next('language','Collect useful language')}</section>`;}
  function language(c){return `<section class="l01-step"><div class="l01-step-head"><span>07 • LANGUAGE BANK</span><h2>Collect words that rebuild the park quickly.</h2></div><div class="l01-language-bank v72-language-bank">${(c.languageBank||[]).map((p,i)=>{const id=`language-${i}`,s=status('phrase',id);return `<article class="v72-language-item${cls('phrase',id)}" data-personal-key="${esc(s.key)}"><div><i>${String(i+1).padStart(2,'0')}</i><b>${esc(p)}</b></div><div class="v72-row-actions"><button data-eng-v52-click="speak('${q(p)}',.82)">${icon('volume')} Listen</button>${tools('phrase',id,p,p,'Language Bank')}</div></article>`;}).join('')}</div><div class="l01-memory-grid"><article><span>DESCRIPTION FRAMES</span>${(c.memoryFrames||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</article><article><span>PERSONAL TRANSFER</span>${(c.personalQuestions||[]).map((x,i)=>`<p><i>${i+1}</i>${esc(x)}</p>`).join('')}</article></div>${next('grammar','Open grammar + model ladder')}</section>`;}
  function grammar(c){const models=c.grammar?.models||{},level=state.level&&models[state.level]?state.level:(models['B1–B2']?'B1–B2':Object.keys(models)[0]);return `<section class="l01-step"><div class="l01-step-head"><span>08 • GRAMMAR & MODEL LADDER</span><h2>${esc(c.grammar.title)}</h2><p>${esc(c.grammar.explainer)}</p></div><div class="v73-memory-contrast"><article><span>PHOTO NOW</span><p>The children are running hand in hand beside the playground.</p></article><article><span>YOUR MEMORY</span><p>When I was a child, I used to play in parks after school.</p></article><article><span>DO NOT INVENT</span><p>Do not say these photographed children “used to” do something unless outside context provides that history.</p></article></div><div class="l01-grammar-examples v72-grammar-examples">${(c.grammar.examples||[]).map((e,i)=>{const id=`example-${i}`,s=status('grammar',id);return `<article class="${cls('grammar',id)}" data-personal-key="${esc(s.key)}"><i>${i+1}</i><p>${highlightGrammar(e)}</p><div class="v72-row-actions"><button data-eng-v52-click="speak('${q(e)}',.82)">${icon('volume')} Listen</button>${tools('grammar',id,`Grammar example ${i+1}`,e,'Grammar Example')}</div></article>`;}).join('')}</div><div class="model-ladder l01-model-ladder"><div class="level-switch">${Object.keys(models).map(l=>`<button class="${level===l?'active':''}" data-eng-v52-click="state.level='${q(l)}';render()">${esc(l)}</button>`).join('')}</div><article><div><span>SCENE MODEL</span><button data-eng-v52-click="speak('${q(models[level])}',.88)">${icon('volume')} Listen</button></div><p>${esc(models[level])}</p></article></div><div class="l01-model-progression v72-model-progression">${Object.entries(models).map(([l,t])=>{const id=`model-${String(l).toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,s=status('grammar',id);return `<article class="${cls('grammar',id)}" data-personal-key="${esc(s.key)}"><span>${esc(l)}</span><p>${esc(t)}</p><div class="v72-row-actions"><button data-eng-v52-click="speak('${q(t)}',.86)">${icon('volume')} Listen</button>${tools('grammar',id,`${l} model`,t,'Grammar Model')}</div></article>`;}).join('')}</div>${next('speak','Describe it yourself')}</section>`;}
  function speakStep(c){return `<section class="l01-step"><div class="l01-step-head"><span>09 • INDEPENDENT SPEAKING</span><h2>Rebuild the park scene in your own English.</h2><p>Describe the photograph first. Use past-habit grammar only as a clearly separate personal-memory extension.</p></div><div class="l01-speaking-stages">${[['30','30 SEC','Simple scene'],['60','60 SEC','Connected description'],['90','90 SEC','Full reconstruction']].map(([sec,label,title])=>`<article><i>${label}</i><h3>${title}</h3><p>${esc(c.speaking[sec])}</p><button data-eng-v52-click="launchTimedVoiceChallenge(${sec})">Record ${sec}s ${icon('mic')}</button></article>`).join('')}</div><div class="l01-selfcheck"><span>SELF-CHECK</span><div><i>${icon('check')} 5+ visible facts</i><i>${icon('check')} movement described</i><i>${icon('check')} playground + park details</i><i>${icon('check')} 1 cautious inference</i><i>${icon('check')} no exact ages/parent claims</i><i>${icon('check')} memory grammar clearly separated</i></div></div><div class="l01-finish-row"><button data-eng-v52-click="setMode('talk')">Continue to scene conversation ${icon('spark')}</button><button class="secondary" data-eng-v52-click="setL03JourneyStep('overview')">Review lesson path</button></div></section>`;}
  function body(c){if(state.l03JourneyStep==='overview')return overview(c);if(state.l03JourneyStep==='micro')return micro(c);if(state.l03JourneyStep==='build')return build(c);if(state.l03JourneyStep==='scenario')return scenario(c);if(state.l03JourneyStep==='meaning')return meaning(c);if(state.l03JourneyStep==='story')return story(c);if(state.l03JourneyStep==='language')return language(c);if(state.l03JourneyStep==='grammar')return grammar(c);return speakStep(c);}
  function complete(){const c=g();if(!['overview','micro','build','scenario','meaning','story','language','grammar','speak'].includes(state.l03JourneyStep))state.l03JourneyStep='overview';return `<section class="l01-complete-path"><div class="panel-heading l01-path-heading"><div><span class="section-kicker">LESSON 03 • COMPLETE LEARNING JOURNEY</span><h2>See → move → combine → reason → remember → speak</h2><p>${state.lesson?.hotspots?.length||0} categorized park anchors connect visual detail, movement language, scene combinations, evidence control, personal-memory grammar and independent speaking.</p></div><div class="l01-path-count"><b>${state.lesson?.hotspots?.length||0}</b><span>image anchors</span></div></div>${nav()}${body(c)}</section>`;}
  const _learn=learnContent;
  learnContent=function(){if(activeLessonId()===3)return complete();return _learn();};

  // Deep-link marked Lesson 03 learning items to their exact stage.
  const _openPersonal=root.openPersonalMark;
  root.openPersonalMark=function(key){const item=PM?.list(progress).find(x=>x.key===key);if(!item||Number(item.lessonId)!==3||!['sentence','phrase','grammar'].includes(item.type))return _openPersonal?.(key);root.closeMyMarksLibrary?.();openLesson(3);setMode('learn');if(item.type==='sentence')state.l03JourneyStep='build';if(item.type==='phrase')state.l03JourneyStep='language';if(item.type==='grammar')state.l03JourneyStep='grammar';render();setTimeout(()=>{const el=[...document.querySelectorAll('[data-personal-key]')].find(x=>x.dataset.personalKey===key);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('v72-focus-pulse');setTimeout(()=>el.classList.remove('v72-focus-pulse'),1800);}},100);};

  const _open=openLesson;
  openLesson=function(id){if(Number(id)===3){state.l03JourneyStep='overview';state.hotspotCategoryByLesson=state.hotspotCategoryByLesson||{};state.hotspotCategoryByLesson[3]='overview';}return _open(id);};
  root.ENGBOOK_RUNTIME={...(root.ENGBOOK_RUNTIME||{}),build:BUILD_INFO.tag,lesson03CompleteLearningJourney:true,lesson03Hotspots:'dynamic-truth-audited',lesson03TaxonomyProfile:'children-park-play',lesson03CategoryCount:8,lesson03SentenceCoverage:'all-retained-hotspots',lesson03GrammarLadderCoverage:'all-retained-hotspots',lesson03SceneCombinationCount:7};
})(typeof window!=='undefined'?window:globalThis);
